# Generated by Django 3.1 on 2021-02-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=15)),
                ('apellido', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
                ('imagen', models.ImageField(blank=True, upload_to=None)),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('fechaRegistro', models.DateField(auto_now=True, verbose_name='Fecha del día de hoy')),
                ('telcel', models.CharField(choices=[('cel', 'Celular'), ('tel', 'Telefono')], default='tel', max_length=3, verbose_name='Telefono o Celular')),
                ('numero', models.IntegerField(default=1)),
            ],
        ),
    ]
