# Generated by Django 3.1 on 2021-03-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_remove_persona_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telcel',
            field=models.CharField(choices=[('Cel', 'Celular'), ('Tel', 'Telefono')], default='Tel', max_length=3, verbose_name='Telefono o Celular'),
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denuncia', models.CharField(max_length=300)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
        ),
    ]
