# Generated by Django 3.1 on 2021-03-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210310_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='persona',
        ),
        migrations.AddField(
            model_name='persona',
            name='denuncias',
            field=models.ManyToManyField(to='persona.Denuncia'),
        ),
    ]
