# Generated by Django 3.1 on 2021-03-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20210310_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='caratula',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
