# Generated by Django 3.1 on 2021-03-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_auto_20210310_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='denuncias',
        ),
        migrations.AddField(
            model_name='persona',
            name='denuncias',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
    ]
