# Generated by Django 3.1 on 2021-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_auto_20210311_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='denuncias',
            field=models.TextField(),
        ),
    ]
