# Generated by Django 3.2.4 on 2021-07-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20210311_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechaNac',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
