# Generated by Django 3.1 on 2021-03-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20210306_1057'),
        ('persona', '0002_remove_persona_imagen'),
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='adoptante',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adopcion',
            name='animal',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adopcion',
            name='solicitud',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
