# Generated by Django 3.1 on 2021-02-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre de vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('especie', models.CharField(max_length=15)),
                ('raza', models.CharField(max_length=15)),
                ('sexo', models.CharField(choices=[('hem', 'Hembra'), ('mac', 'Macho')], default='mac', max_length=3)),
                ('castrado', models.BooleanField(default=False)),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('fechaPub', models.DateField(auto_now=True, verbose_name='Fecha del día de hoy')),
                ('Dueño', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('vacuna', models.ManyToManyField(to='mascota.Vacuna')),
            ],
        ),
    ]
