# Generated by Django 3.1 on 2021-03-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20210306_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default=0, upload_to='adopcionesweb/static/media'),
            preserve_default=False,
        ),
    ]
