# Generated by Django 3.2.4 on 2021-07-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20210310_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fechaNac',
            field=models.DateField(default=1, verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
    ]
